(function(){
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const $=s=>document.querySelector(s);
  let token=sessionStorage.getItem('jamrat_admin_token')||'';
  let active='events', selectedEvent=sessionStorage.getItem('jcc_event')||'';
  const call=async(path,opt={})=>{
    const headers={'Content-Type':'application/json',...(opt.headers||{})};
    const t=token||sessionStorage.getItem('jamrat_admin_token')||''; if(t) headers.Authorization='Bearer '+t;
    const r=await fetch('/.netlify/functions/'+path,{...opt,credentials:'same-origin',headers});
    let d={}; try{d=await r.json()}catch{}
    if(r.status===401){token='';sessionStorage.removeItem('jamrat_admin_token');showLogin('انتهت جلسة الإدارة، سجلي الدخول مرة أخرى.');throw new Error('AUTH_REQUIRED')}
    if(!r.ok||d.ok===false) throw new Error(d.message||('HTTP '+r.status)); return d;
  };
  const modal=document.createElement('div'); modal.id='jamrat-control-center'; modal.innerHTML=`<style>
  #jcc-btn{position:fixed;bottom:18px;left:18px;z-index:99998;background:#0f0e0d;color:#fff;border:1px solid #c5a059;border-radius:999px;padding:11px 16px;font-weight:800;box-shadow:0 8px 30px #0004;cursor:pointer}
  #jcc-mask{position:fixed;inset:0;background:#0008;z-index:99999;display:none;align-items:center;justify-content:center;padding:16px}
  #jcc{width:min(1180px,100%);max-height:94vh;overflow:auto;background:#fffaf3;color:#161411;border-radius:24px;box-shadow:0 20px 70px #0007;border:1px solid #c5a059}
  #jcc .hd{padding:18px 20px;background:#0f0e0d;color:#fff;border-radius:24px 24px 0 0;display:flex;justify-content:space-between;align-items:center;gap:10px}
  #jcc .tabs{display:flex;gap:6px;padding:10px;overflow:auto;border-bottom:1px solid #eadfca;position:sticky;top:0;background:#fffaf3;z-index:2}
  #jcc .tab{border:1px solid #d9ccb3;background:#fff;padding:9px 12px;border-radius:12px;cursor:pointer;font-weight:700;white-space:nowrap}.tab.on{background:#c5a059;color:#0f0e0d}
  #jcc .body{padding:18px}.jcc-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.jcc-card{background:#fff;border:1px solid #e6dcc8;border-radius:18px;padding:16px}.jcc-card h3{margin:0 0 12px}.jcc-input,.jcc-select,.jcc-text{width:100%;padding:11px;border:1px solid #d7cbb7;border-radius:10px;background:#fff;box-sizing:border-box;margin:4px 0}.jcc-text{min-height:110px;resize:vertical}.jcc-row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.jcc-btn{border:0;border-radius:10px;padding:10px 14px;font-weight:800;cursor:pointer;background:#0f0e0d;color:#fff}.jcc-btn.gold{background:#c5a059;color:#0f0e0d}.jcc-btn.red{background:#b42318}.jcc-btn.ghost{background:#fff;color:#0f0e0d;border:1px solid #d7cbb7}.jcc-muted{font-size:12px;opacity:.65}.jcc-status{margin-top:10px;padding:10px;border-radius:10px;background:#f6f1e7;white-space:pre-wrap}.ok{color:#087443;font-weight:800}.bad{color:#b42318;font-weight:800}.jcc-table{width:100%;border-collapse:collapse;font-size:12px}.jcc-table th,.jcc-table td{padding:9px;border-bottom:1px solid #eee1ca;text-align:right}.jcc-pill{display:inline-block;padding:4px 8px;border-radius:99px;background:#f3ead8;font-size:11px;font-weight:700}.jcc-login{max-width:420px;margin:auto}.jcc-hidden{display:none!important}
  body[data-jamrat-theme="dark"] #jcc{background:#111;color:#f7f4ed;border-color:#c5a059} body[data-jamrat-theme="dark"] #jcc .tabs{background:#111;border-color:#333} body[data-jamrat-theme="dark"] #jcc .tab,.dark-jcc .tab{background:#1b1b1b;color:#f7f4ed;border-color:#444} body[data-jamrat-theme="dark"] #jcc .jcc-card{background:#181818;border-color:#333} body[data-jamrat-theme="dark"] #jcc .jcc-input,body[data-jamrat-theme="dark"] #jcc .jcc-select,body[data-jamrat-theme="dark"] #jcc .jcc-text{background:#101010;color:#fff;border-color:#444} body[data-jamrat-theme="dark"] #jcc .jcc-status{background:#222} body[data-jamrat-theme="dark"] #jcc .jcc-btn.ghost{background:#181818;color:#fff;border-color:#444}
  @media(max-width:700px){.jcc-grid{grid-template-columns:1fr}}
  </style><button id="jcc-btn">🛠️ مركز التشغيل الكامل</button><div id="jcc-mask"><div id="jcc"><div class="hd"><div><b>جمرة غضى — V9.1</b><div class="jcc-muted" style="color:#ddd">إدارة المناسبة • الضيوف • الإرسال • الوسائط • QR • البوت • التكاملات</div></div><div class="jcc-row"><button id="jcc-theme" class="jcc-btn ghost">🌙 الوضع</button><button id="jcc-close" class="jcc-btn">إغلاق</button></div></div><div class="tabs">${[['events','🗓️ المناسبات'],['guests','👥 الضيوف'],['media','🎬 الوسائط'],['send','📤 الإرسال'],['integrations','⚙️ التكاملات'],['qr','🔗 QR'],['schedule','⏰ التذكير والشكر'],['archive','📦 الأرشيف'],['logs','📋 سجل الإرسال'],['bot','🤖 البوت وFAQ'],['admin','🛠️ الإدارة']].map(([a,b])=>`<button class="tab" data-t="${a}">${b}</button>`).join('')}</div><div class="body" id="jcc-body"></div></div></div>`;document.body.appendChild(modal);
  const body=$('#jcc-body');
  function status(m,ok=true){return `<div class="jcc-status ${ok?'ok':'bad'}">${esc(m)}</div>`}
  function showLogin(msg=''){active='login';body.innerHTML=`<div class="jcc-login jcc-card"><h3>🔐 دخول الإدارة</h3><p class="jcc-muted">هذه الجلسة مطلوبة للعمليات التي تكتب في Firestore أو تستخدم مفاتيح الإرسال.</p><input id="login-user" class="jcc-input" placeholder="اسم المستخدم" autocomplete="username"><input id="login-pass" class="jcc-input" type="password" placeholder="كلمة المرور" autocomplete="current-password"><button id="login-go" class="jcc-btn gold">دخول آمن</button><div id="login-status">${msg?status(msg,false):''}</div></div>`;$('#login-go').onclick=async()=>{try{const u=$('#login-user').value.trim(),p=$('#login-pass').value;if(!u||!p)throw new Error('اسم المستخدم وكلمة المرور مطلوبان');const d=await fetch('/.netlify/functions/admin-session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:u,password:p})}).then(async r=>{const x=await r.json();if(!r.ok||!x.ok)throw new Error(x.message||'فشل الدخول');return x});token=d.token;sessionStorage.setItem('jamrat_admin_token',token);active='events';render()}catch(e){$('#login-status').innerHTML=status(e.message,false)}}}
  async function getEvents(){const d=await call('events-list');return d.events||[]}
  function render(){
    document.querySelectorAll('#jcc .tab').forEach(x=>x.classList.toggle('on',x.dataset.t===active));
    if(!token && active!=='login'){showLogin();return}
    if(active==='events') body.innerHTML=`<div class="jcc-grid"><div class="jcc-card"><h3>➕ إنشاء / تعديل مناسبة</h3><input id="ev-code" class="jcc-input" placeholder="رمز المناسبة (فريد)"><input id="ev-client" class="jcc-input" placeholder="اسم العميل/ة"><input id="ev-title" class="jcc-input" placeholder="عنوان المناسبة"><input id="ev-date" class="jcc-input" type="datetime-local"><input id="ev-email" class="jcc-input" placeholder="إيميل العميل للتقارير"><input id="ev-slug" class="jcc-input" placeholder="الرابط المخصص مثل sara-ahmed"><select id="ev-mode" class="jcc-select"><option value="full">تطبيق كامل</option><option value="hybrid">تطبيق + موقع RSVP</option></select><select id="ev-template" class="jcc-select"><option value="wedding-vip">wedding-vip</option><option value="corporate">corporate</option><option value="wedding-gold">wedding-gold</option><option value="graduation-luxury">graduation-luxury</option><option value="baby-boy">baby-boy</option><option value="baby-girl">baby-girl</option><option value="conference">conference</option><option value="wedding-classic">wedding-classic</option><option value="wedding-modern">wedding-modern</option><option value="wedding-pink">wedding-pink</option><option value="wedding-royal">wedding-royal</option><option value="wedding-silver">wedding-silver</option><option value="graduation-classic">graduation-classic</option></select><button id="ev-save" class="jcc-btn gold">حفظ المناسبة</button><div id="ev-status"></div></div><div class="jcc-card"><h3>📋 المناسبات الحالية</h3><button id="ev-refresh" class="jcc-btn">تحديث</button><div id="ev-list" style="margin-top:10px">جاري التحميل...</div></div></div>`;
    if(active==='guests') body.innerHTML=`<div class="jcc-grid"><div class="jcc-card"><h3>👥 قائمة الضيوف</h3><input id="g-event" class="jcc-input" placeholder="Event ID" value="${esc(selectedEvent)}"><textarea id="g-data" class="jcc-text" placeholder='ألصقي JSON أو CSV. JSON مثال: [{"name":"سارة","phone":"9665...","email":"a@b.com","companions":2}]'></textarea><div class="jcc-row"><button id="g-import" class="jcc-btn gold">استيراد</button><button id="g-load" class="jcc-btn">عرض القائمة</button></div><div id="g-status"></div></div><div class="jcc-card"><h3>🔗 بيانات الضيف</h3><p class="jcc-muted">كل ضيف يحصل على personalCode ويمكن استخدامه في رابط Hybrid وQR.</p><div id="g-list"></div></div></div>`;
    if(active==='media') body.innerHTML=`<div class="jcc-grid"><div class="jcc-card"><h3>🎬 رفع فيديو أو صورة من الجهاز</h3><input id="m-event" class="jcc-input" placeholder="Event ID" value="${esc(selectedEvent)}"><select id="m-kind" class="jcc-select"><option value="invitationVideoUrl">فيديو الدعوة</option><option value="reminderVideoUrl">فيديو التذكير</option><option value="thankyouVideoUrl">فيديو الشكر</option></select><input id="m-file" type="file" accept="video/*,image/*" class="jcc-input"><button id="m-upload" class="jcc-btn gold">رفع وحفظ</button><div id="m-status"></div></div><div class="jcc-card"><h3>☁️ Cloudinary</h3><input id="m-cloud" class="jcc-input" placeholder="رابط Cloudinary العام"><select id="m-cloud-kind" class="jcc-select"><option value="invitationVideoUrl">فيديو الدعوة</option><option value="reminderVideoUrl">فيديو التذكير</option><option value="thankyouVideoUrl">فيديو الشكر</option></select><button id="m-save-cloud" class="jcc-btn">حفظ الرابط</button><div id="mc-status"></div><p class="jcc-muted">الفيديو ≤ 15MB من الجهاز. الرابط العام يجب أن يكون متاحًا لـMeta/Resend.</p></div></div>`;
    if(active==='send') body.innerHTML=`<div class="jcc-grid"><div class="jcc-card"><h3>📤 إرسال حسب القناة</h3><input id="s-event" class="jcc-input" placeholder="Event ID" value="${esc(selectedEvent)}"><input id="s-to" class="jcc-input" placeholder="رقم WhatsApp أو البريد"><input id="s-subject" class="jcc-input" placeholder="عنوان البريد"><textarea id="s-text" class="jcc-text" placeholder="نص الدعوة/التذكير/الشكر"></textarea><input id="s-video" class="jcc-input" placeholder="رابط الفيديو"><input id="s-card" class="jcc-input" placeholder="رابط الصورة"><div class="jcc-row"><button id="send-wa" class="jcc-btn gold">WhatsApp</button><button id="send-email" class="jcc-btn">Email</button></div><div id="send-status"></div></div><div class="jcc-card"><h3>🧾 إرسال للضيوف</h3><p class="jcc-muted">استخدمي تبويب الضيوف لاستيراد القائمة، ثم اختاري القناة هنا لإرسال اختبار لرقم/إيميل واحد. الإرسال الجماعي الكامل يحتاج قائمة الضيوف + طابور، ويظهر كل نجاح/فشل في السجل.</p></div></div>`;
    if(active==='integrations') body.innerHTML=`<div class="jcc-card"><h3>⚙️ WhatsApp / Resend / Cloudinary</h3><div class="jcc-grid">${[['whatsappToken','WhatsApp Token'],['whatsappPhoneId','WhatsApp Phone ID'],['resendApiKey','Resend API Key'],['sendFrom','Email From'],['cloudinaryCloudName','Cloudinary Cloud Name'],['cloudinaryApiKey','Cloudinary API Key'],['cloudinaryApiSecret','Cloudinary API Secret'],['siteBaseUrl','رابط موقعك الحقيقي'],['netlifySiteUrl','رابط Netlify للتطبيق'],['firebaseProjectId','Firebase Project ID'],['firebaseWebApiKey','Firebase Web API Key']].map(([k,l])=>`<div><label>${l}</label><input class="jcc-input int" data-k="${k}" type="password" placeholder="${l}"><button class="jcc-btn red int-del" data-k="${k}">حذف</button></div>`).join('')}</div><div class="jcc-row"><button id="load-int" class="jcc-btn">فحص الإعدادات</button><button id="save-int" class="jcc-btn gold">حفظ</button></div><div id="int-status"></div><p class="jcc-muted">المفاتيح تحفظ على السيرفر فقط ولا تعاد قيمتها للمتصفح.</p></div>`;
    if(active==='qr') body.innerHTML=`<div class="jcc-grid"><div class="jcc-card"><h3>🔗 QR صفحة تأكيد الحضور</h3><input id="qr-url" class="jcc-input" placeholder="https://jamratghadah.com/...؟eid=...&g=..."><button id="make-qr" class="jcc-btn gold">توليد QR</button><button id="dl-qr" class="jcc-btn">تحميل PNG</button><div id="qr-box" style="margin-top:15px;display:grid;place-items:center;min-height:230px"></div></div><div class="jcc-card"><h3>🎨 التصميم</h3><p>الـQR: أسود + ذهبي، والخلفية شفافة عند التصدير.</p></div></div>`;
    if(active==='schedule') body.innerHTML=`<div class="jcc-grid"><div class="jcc-card"><h3>⏰ تذكير</h3><input id="sc-event" class="jcc-input" placeholder="Event ID"><input id="rem-days" type="number" min="0" value="7" class="jcc-input" placeholder="قبل كم يوم"><input id="rem-time" type="time" value="19:00" class="jcc-input"><input id="rem-video" class="jcc-input" placeholder="فيديو التذكير URL"><button id="save-rem" class="jcc-btn gold">حفظ — مرة واحدة</button><div id="rem-status"></div></div><div class="jcc-card"><h3>💛 شكر</h3><input id="thank-days" type="number" min="0" value="1" class="jcc-input" placeholder="بعد كم يوم"><input id="thank-time" type="time" value="12:00" class="jcc-input"><input id="thank-video" class="jcc-input" placeholder="فيديو الشكر URL"><button id="save-thank" class="jcc-btn">حفظ — للحاضرين فقط</button><div id="thank-status"></div></div></div>`;
    if(active==='archive') body.innerHTML=`<div class="jcc-card"><h3>📦 الأرشيف</h3><input id="arc-event" class="jcc-input" placeholder="Event ID"><div class="jcc-row"><button id="arc-now" class="jcc-btn gold">أرشفة</button><button id="restore" class="jcc-btn">استعادة</button><button id="arc-auto" class="jcc-btn ghost">تشغيل الأرشفة التلقائية الآن</button></div><div id="arc-status"></div></div>`;
    if(active==='logs') body.innerHTML=`<div class="jcc-card"><div class="jcc-row"><h3 style="margin-inline-end:auto">📋 سجل الإرسال</h3><button id="refresh-logs" class="jcc-btn">تحديث</button><button id="clear-logs" class="jcc-btn red">حذف السجل</button></div><table class="jcc-table"><thead><tr><th>الوقت</th><th>المناسبة</th><th>الضيف</th><th>القناة</th><th>المستلم</th><th>النتيجة</th><th></th></tr></thead><tbody id="logs-body"><tr><td colspan="7">جاري التحميل...</td></tr></tbody></table></div>`;
    if(active==='bot') body.innerHTML=`<div class="jcc-grid"><div class="jcc-card"><h3>🤖 سؤال الضيف</h3><input id="faq-q" class="jcc-input" placeholder="اكتبي السؤال"><button id="faq-search" class="jcc-btn gold">بحث</button><div id="faq-answer"></div></div><div class="jcc-card"><h3>➕ FAQ</h3><input id="faq-question" class="jcc-input" placeholder="السؤال"><textarea id="faq-response" class="jcc-text" placeholder="الإجابة"></textarea><button id="faq-save" class="jcc-btn">حفظ</button><div id="faq-save-status"></div></div></div>`;
    if(active==='admin') body.innerHTML=`<div class="jcc-grid"><div class="jcc-card"><h3>🛠️ أدوات الإدارة</h3><div class="jcc-row"><button id="open-admin" class="jcc-btn gold">فتح admin-tools.html</button><button id="health" class="jcc-btn">فحص صحة النظام</button></div><div id="health-status"></div></div><div class="jcc-card"><h3>🔒 الجلسة</h3><button id="logout-admin" class="jcc-btn red">تسجيل خروج الإدارة</button><p class="jcc-muted">التوكن محفوظ في sessionStorage فقط ويزول بإغلاق الجلسة/تسجيل الخروج.</p></div></div>`;
    bind();
    if(active==='events') loadEvents(); if(active==='guests') loadGuests(); if(active==='logs') loadLogs();
  }
  async function loadEvents(){try{const ev=await getEvents();$('#ev-list').innerHTML=ev.length?ev.map(e=>`<div class="jcc-card" style="margin-top:8px;padding:10px"><b>${esc(e.title||e.eventCode)}</b><div class="jcc-muted">${esc(e.eventCode)} • ${esc(e.eventDate||'')} • ${esc(e.status||'active')} ${e.archived?'<span class="jcc-pill">مؤرشفة</span>':''}</div><button class="jcc-btn ghost" data-use-event="${esc(e.eventCode||e.id)}">استخدام</button></div>`).join(''):'لا توجد مناسبات';document.querySelectorAll('[data-use-event]').forEach(b=>b.onclick=()=>{selectedEvent=b.dataset.useEvent;sessionStorage.setItem('jcc_event',selectedEvent);$('#g-event')?.setAttribute('value',selectedEvent);});}catch(e){$('#ev-list').innerHTML=status(e.message,false)}}
  async function loadGuests(){try{const d=await call('guests?eventId='+encodeURIComponent(selectedEvent||$('#g-event')?.value||''));$('#g-list').innerHTML=(d.guests||[]).map(g=>`<div class="jcc-card" style="padding:10px;margin-top:7px"><b>${esc(g.name)}</b><div class="jcc-muted">${esc(g.phone||g.email||'')} • مرافقون: ${esc(g.companions??0)} • ${g.confirmed?'أكد الحضور':'لم يؤكد'}</div><div class="jcc-muted">personalCode: ${esc(g.personalCode||'')}</div><button class="jcc-btn ghost guest-rsvp" data-code="${esc(g.personalCode||g.entryCode||'')}">🔗 رابط RSVP + QR</button></div>`).join('')||'لا يوجد ضيوف';await bindGuestLinks();}catch(e){$('#g-list').innerHTML=status(e.message,false)}}
  async function bindGuestLinks(){document.querySelectorAll('.guest-rsvp').forEach(b=>b.onclick=async()=>{try{const d=await call('events-list');const ev=(d.events||[]).find(x=>String(x.eventCode||x.id)===String(selectedEvent));if(!ev)throw new Error('المناسبة غير موجودة');const base=ev.siteBaseUrl||ev.siteUrl||'';const slug=ev.coupleSlug||ev.slug||'';const site=base||'https://jamratghadah.com';if(!slug)throw new Error('الرابط المخصص للمناسبة غير موجود');const url=site.replace(/\/$/,'')+'/'+encodeURIComponent(slug)+'?eid='+encodeURIComponent(ev.eventCode||selectedEvent)+'&g='+encodeURIComponent(b.dataset.code);$('#qr-url')?.setAttribute('value',url);active='qr';render();setTimeout(()=>{$('#qr-url').value=url;$('#make-qr').click()},50)}catch(e){alert(e.message)}})}
  async function loadLogs(){try{const d=await call('send-log');$('#logs-body').innerHTML=(d.logs||[]).map(x=>`<tr><td>${esc(x.createdAt?.toDate?x.createdAt.toDate().toLocaleString('ar-SA'):x.time||'')}</td><td>${esc(x.eventId)}</td><td>${esc(x.guestId)}</td><td>${esc(x.channel)}</td><td>${esc(x.to)}</td><td class="${x.ok?'ok':'bad'}">${x.ok?'نجح':'فشل'} — ${esc(x.message||'')}</td><td><button class="jcc-btn red" data-del-log="${esc(x.id)}">حذف</button></td></tr>`).join('')||'<tr><td colspan="7">لا يوجد سجل</td></tr>';document.querySelectorAll('[data-del-log]').forEach(b=>b.onclick=async()=>{await call('send-log?id='+encodeURIComponent(b.dataset.delLog),{method:'DELETE'});loadLogs()})}catch(e){$('#logs-body').innerHTML=`<tr><td colspan="7">${esc(e.message)}</td></tr>`}}
  function bind(){
    $('#ev-save')?.addEventListener('click',async()=>{try{const localDate=$('#ev-date').value.trim(); const tz=Intl.DateTimeFormat().resolvedOptions().timeZone||'Asia/Riyadh'; const p={eventCode:$('#ev-code').value.trim(),clientName:$('#ev-client').value.trim(),title:$('#ev-title').value.trim(),eventDate:localDate,clientEmail:$('#ev-email').value.trim(),slug:$('#ev-slug').value.trim(),coupleSlug:$('#ev-slug').value.trim(),template:$('#ev-template').value,eventType:$('#ev-mode').value,mode:$('#ev-mode').value,timeZone:tz};if(!p.eventCode||!p.clientName)throw new Error('رمز المناسبة واسم العميل/ة مطلوبان');await call('event-register',{method:'POST',body:JSON.stringify(p)});selectedEvent=p.eventCode;sessionStorage.setItem('jcc_event',selectedEvent);$('#ev-status').innerHTML=status('تم حفظ المناسبة وربطها بالمصدر الموحد');loadEvents()}catch(e){$('#ev-status').innerHTML=status(e.message,false)}});
    $('#ev-refresh')?.addEventListener('click',loadEvents);
    $('#g-import')?.addEventListener('click',async()=>{try{const eid=$('#g-event').value.trim();selectedEvent=eid;sessionStorage.setItem('jcc_event',eid);let raw=$('#g-data').value.trim();let rows;try{rows=JSON.parse(raw)}catch{rows=raw.split(/\r?\n/).filter(Boolean).map(line=>{const [name,phone,email,companions]=line.split(',').map(x=>x.trim());return{name,phone,email,companions:Number(companions||0)}})}if(!eid||!Array.isArray(rows)||!rows.length)throw new Error('Event ID وقائمة الضيوف مطلوبة');await call('guests',{method:'POST',body:JSON.stringify({eventId:eid,guests:rows})});$('#g-status').innerHTML=status('تم استيراد '+rows.length+' ضيف');loadGuests()}catch(e){$('#g-status').innerHTML=status(e.message,false)}});$('#g-load')?.addEventListener('click',()=>{selectedEvent=$('#g-event').value.trim();sessionStorage.setItem('jcc_event',selectedEvent);loadGuests()});
    $('#m-upload')?.addEventListener('click',async()=>{try{const f=$('#m-file').files[0],eid=$('#m-event').value.trim(),kind=$('#m-kind').value;if(!eid||!f)throw new Error('Event ID والفيديو مطلوبان');if(f.size>15*1024*1024)throw new Error('الملف أكبر من 15MB');const isImage=f.type.startsWith('image/'); const sig=await call('cloudinary-signature',{method:'POST',body:JSON.stringify({folder:'jamrat/invitations',resourceType:isImage?'image':'video'})});const fd=new FormData();fd.append('file',f);fd.append('api_key',sig.apiKey);fd.append('timestamp',sig.timestamp);fd.append('folder',sig.folder);fd.append('signature',sig.signature);const up=await fetch(`https://api.cloudinary.com/v1_1/${encodeURIComponent(sig.cloudName)}/${isImage?'image':'video'}/upload`,{method:'POST',body:fd});const d=await up.json();if(!up.ok||!d.secure_url)throw new Error(d.error?.message||'فشل Cloudinary');const saveKey=isImage?(kind==='invitationVideoUrl'?'invitationImageUrl':kind==='reminderVideoUrl'?'reminderImageUrl':'thankyouImageUrl'):kind; await call('event-media',{method:'POST',body:JSON.stringify({eventId:eid,[saveKey]:d.secure_url})});$('#m-status').innerHTML=status('تم رفع الفيديو وحفظه للمناسبة')}catch(e){$('#m-status').innerHTML=status(e.message,false)}});
    $('#m-save-cloud')?.addEventListener('click',async()=>{try{const eid=$('#m-event').value.trim(),url=$('#m-cloud').value.trim(),kind=$('#m-cloud-kind').value;if(!eid||!url)throw new Error('Event ID والرابط مطلوبان');await call('event-media',{method:'POST',body:JSON.stringify({eventId:eid,[kind]:url})});$('#mc-status').innerHTML=status('تم حفظ رابط Cloudinary')}catch(e){$('#mc-status').innerHTML=status(e.message,false)}});
    const send=async ch=>{try{const to=$('#s-to').value.trim(),text=$('#s-text').value.trim();if(!to)throw new Error('المستلم مطلوب');const p=ch==='WhatsApp'?{to,message:text,videoUrl:$('#s-video').value.trim(),cardUrl:$('#s-card').value.trim()}:{to,subject:$('#s-subject').value.trim(),text,videoUrl:$('#s-video').value.trim(),cardUrl:$('#s-card').value.trim()};const d=await call(ch==='WhatsApp'?'send-whatsapp':'send-email',{method:'POST',body:JSON.stringify(p)});await call('send-log',{method:'POST',body:JSON.stringify({eventId:$('#s-event').value.trim(),channel:ch,to,ok:true,message:d.message||d.messageId||JSON.stringify(d.results||'تم')})});$('#send-status').innerHTML=status('تم الإرسال بنجاح عبر '+ch)}catch(e){try{await call('send-log',{method:'POST',body:JSON.stringify({eventId:$('#s-event')?.value.trim()||'',channel:ch,to:$('#s-to')?.value.trim()||'',ok:false,message:e.message})})}catch{}$('#send-status').innerHTML=status(e.message,false)}};
    $('#send-wa')?.addEventListener('click',()=>send('WhatsApp'));$('#send-email')?.addEventListener('click',()=>send('Email'));
    $('#save-int')?.addEventListener('click',async()=>{try{for(const i of document.querySelectorAll('.int'))if(i.value.trim())await call('integration-settings?key='+encodeURIComponent(i.dataset.k),{method:'POST',body:JSON.stringify({key:i.dataset.k,value:i.value.trim()})});$('#int-status').innerHTML=status('تم الحفظ على السيرفر فقط')}catch(e){$('#int-status').innerHTML=status(e.message,false)}});$('#load-int')?.addEventListener('click',async()=>{try{const d=await call('integration-settings');$('#int-status').innerHTML=status('المفعل: '+Object.keys(d.configured||{}).filter(k=>d.configured[k]).join(', ')||'لا شيء')}catch(e){$('#int-status').innerHTML=status(e.message,false)}});document.querySelectorAll('.int-del').forEach(b=>b.onclick=async()=>{try{await call('integration-settings?key='+encodeURIComponent(b.dataset.k),{method:'DELETE'});$('#int-status').innerHTML=status('تم حذف '+b.dataset.k)}catch(e){$('#int-status').innerHTML=status(e.message,false)}});
    $('#make-qr')?.addEventListener('click',async()=>{try{const u=$('#qr-url').value.trim();if(!u)throw new Error('رابط RSVP مطلوب');const box=$('#qr-box');box.innerHTML='';if(!window.QRCode)await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js';s.onload=res;s.onerror=()=>rej(new Error('تعذر تحميل مولد QR'));document.head.appendChild(s)});new QRCode(box,{text:u,width:220,height:220,colorDark:'#0f0e0d',colorLight:'#c5a059',correctLevel:QRCode.CorrectLevel.H});setTimeout(()=>{const c=box.querySelector('canvas');if(c){const x=c.getContext('2d'),im=x.getImageData(0,0,c.width,c.height);for(let i=0;i<im.data.length;i+=4)if(im.data[i]>150&&im.data[i+1]>120&&im.data[i+2]<120)im.data[i+3]=0;x.putImageData(im,0,0)}},120)}catch(e){$('#qr-box').innerHTML=status(e.message,false)}});$('#dl-qr')?.addEventListener('click',()=>{const c=$('#qr-box canvas');if(!c)return;const a=document.createElement('a');a.download='jamrat-rsvp-qr.png';a.href=c.toDataURL('image/png');a.click()});
    const saveSchedule=async kind=>{try{const eid=$('#sc-event').value.trim();if(!eid)throw new Error('Event ID مطلوب');const p=kind==='reminder'?{reminder:{enabled:true,daysBefore:+$('#rem-days').value,time:$('#rem-time').value,videoUrl:$('#rem-video').value.trim()}}:{thankyou:{enabled:true,daysAfter:+$('#thank-days').value,time:$('#thank-time').value,videoUrl:$('#thank-video').value.trim()}};await call('event-schedule',{method:'POST',body:JSON.stringify({eventId:eid,...p})});$('#'+(kind==='reminder'?'rem-status':'thank-status')).innerHTML=status('تم حفظ الجدولة مرة واحدة.');}catch(e){$('#'+(kind==='reminder'?'rem-status':'thank-status')).innerHTML=status(e.message,false)}};$('#save-rem')?.addEventListener('click',()=>saveSchedule('reminder'));$('#save-thank')?.addEventListener('click',()=>saveSchedule('thankyou'));
    const arc=async archived=>{try{const eid=$('#arc-event').value.trim();if(!eid)throw new Error('Event ID مطلوب');await call('event-archive',{method:'POST',body:JSON.stringify({eventCode:eid,archived})});$('#arc-status').innerHTML=status(archived?'تمت الأرشفة':'تمت الاستعادة')}catch(e){$('#arc-status').innerHTML=status(e.message,false)}};$('#arc-now')?.addEventListener('click',()=>arc(true));$('#restore')?.addEventListener('click',()=>arc(false));$('#arc-auto')?.addEventListener('click',async()=>{try{const r=await fetch('/.netlify/functions/auto-archive-events',{headers:{Authorization:'Bearer '+(token||sessionStorage.getItem('jamrat_admin_token')||'')}});const d=await r.json();$('#arc-status').innerHTML=status(d.message||JSON.stringify(d))}catch(e){$('#arc-status').innerHTML=status(e.message,false)}});
    $('#refresh-logs')?.addEventListener('click',loadLogs);$('#clear-logs')?.addEventListener('click',async()=>{await call('send-log',{method:'DELETE'});loadLogs()});
    $('#faq-save')?.addEventListener('click',async()=>{try{const question=$('#faq-question').value.trim(),answer=$('#faq-response').value.trim();if(!question||!answer)throw new Error('السؤال والإجابة مطلوبان');await call('faq',{method:'POST',body:JSON.stringify({question,answer})});$('#faq-save-status').innerHTML=status('تم الحفظ')}catch(e){$('#faq-save-status').innerHTML=status(e.message,false)}});$('#faq-search')?.addEventListener('click',async()=>{try{const q=$('#faq-q').value.trim();const d=await call('faq?q='+encodeURIComponent(q));$('#faq-answer').innerHTML=status(d.answer||'لا توجد إجابة مؤكدة، تم تسجيل السؤال للمراجعة.',!!d.answer)}catch(e){$('#faq-answer').innerHTML=status(e.message,false)}});
    $('#open-admin')?.addEventListener('click',()=>location.href='/admin-tools.html');$('#health')?.addEventListener('click',async()=>{try{const d=await call('admin-health');$('#health-status').innerHTML=status(JSON.stringify(d,null,2))}catch(e){$('#health-status').innerHTML=status(e.message,false)}});$('#logout-admin')?.addEventListener('click',()=>{token='';sessionStorage.removeItem('jamrat_admin_token');showLogin('تم تسجيل الخروج')});
  }
  document.querySelectorAll('#jcc .tab').forEach(x=>x.onclick=()=>{active=x.dataset.t;render()});$('#jcc-btn').onclick=()=>{$('#jcc-mask').style.display='flex';render()};$('#jcc-close').onclick=()=>$('#jcc-mask').style.display='none';$('#jcc-theme').onclick=()=>{document.body.dataset.jamratTheme=document.body.dataset.jamratTheme==='dark'?'light':'dark'};
})();
