const crypto = require('crypto');
const { getFirestore } = require('./firestore-admin');

function b64u(v){return Buffer.from(v).toString('base64url')}
function secret(){return process.env.ADMIN_SESSION_SECRET || ''}
function sign(payload){const head=b64u(JSON.stringify({alg:'HS256',typ:'JWT'}));const body=b64u(JSON.stringify(payload));const sig=crypto.createHmac('sha256',secret()).update(`${head}.${body}`).digest('base64url');return `${head}.${body}.${sig}`}
function verify(token){if(!token||!secret()) throw new Error('AUTH_INVALID');const parts=String(token).split('.');if(parts.length!==3)throw new Error('AUTH_INVALID');const [h,p,s]=parts;const expected=crypto.createHmac('sha256',secret()).update(`${h}.${p}`).digest('base64url');const sBuf=Buffer.from(s);const expBuf=Buffer.from(expected);if(sBuf.length!==expBuf.length||!crypto.timingSafeEqual(sBuf,expBuf))throw new Error('AUTH_INVALID');let data;try{data=JSON.parse(Buffer.from(p,'base64url').toString('utf8'))}catch{throw new Error('AUTH_INVALID')}if(!data.exp||data.exp<Date.now())throw new Error('AUTH_EXPIRED');return data}
function pbkdf2Verify(password, stored){const [saltHex,hashHex]=String(stored||'').split(':');if(!saltHex||!hashHex)return false;const out=crypto.pbkdf2Sync(String(password),Buffer.from(saltHex,'hex'),150000,32,'sha256').toString('hex');return crypto.timingSafeEqual(Buffer.from(out),Buffer.from(hashHex));}
function pbkdf2Hash(password){const salt=crypto.randomBytes(16);const hash=crypto.pbkdf2Sync(String(password),salt,150000,32,'sha256').toString('hex');return `${salt.toString('hex')}:${hash}`}
async function usersCollectionEmpty(){const snap=await getFirestore().collection('users').limit(1).get();return snap.empty}
async function createUser(username,password,role){const uname=String(username||'').trim();if(uname.length<3)throw new Error('USERNAME_INVALID');if(String(password||'').length<8)throw new Error('PASSWORD_TOO_SHORT');const db=getFirestore();const existing=await db.collection('users').where('username','==',uname).limit(1).get();if(!existing.empty)throw new Error('USERNAME_TAKEN');const ref=db.collection('users').doc();await ref.set({username:uname,passwordHash:pbkdf2Hash(password),role:role||'super_admin',createdAt:Date.now()});return ref.id}
async function login(username,password){const snap=await getFirestore().collection('users').where('username','==',String(username)).limit(1).get();if(snap.empty)throw new Error('INVALID_LOGIN');const doc=snap.docs[0];const u=doc.data()||{};if(!pbkdf2Verify(password,u.passwordHash))throw new Error('INVALID_LOGIN');const now=Date.now();return sign({sub:doc.id,username:u.username,role:u.role||'admin',iat:now,exp:now+8*60*60*1000})}
async function requireAdmin(event){const h=event.headers?.authorization||event.headers?.Authorization||'';if(!h.startsWith('Bearer '))throw new Error('AUTH_REQUIRED');return verify(h.slice(7))}
module.exports={login,requireAdmin,verify,sign,pbkdf2Verify,pbkdf2Hash,usersCollectionEmpty,createUser};
